### ISSUE TITLE
Feature request: DLNA support for media-source

### ISSUE THREAD

**Issue by SQ6NTI** [j-a-n/lovelace-wallpanel#182] opened 2023-12-10 12:14 UTC
I am using media-source URL to display images from an album stored on my QNAP NAS (QuMagie app). It is exported via DLNA and attached to Home Assistant. The album URL exported from HA is in the following form: `media-source://dlna_dms/nasXXXXXX/:A0$DDD$DDD$DDDDDDDD` ("X" are hex and "D" are decimal identifiers).

The extracted image URLs are in the following form: `http://nas_ip:8200/Resized/A0$DDD$DDD$DDDDDDDD$image_file.jpg?type=2,fid=1,ori=1,width=1423,height=800,ext=.jpg` and they got prefixed with my HA instance URL `http://ha.lan:8123`, forming a broken URL.

My quick and dirty hack was to remove `${document.location.origin}` from [wallpanel.js#L1772](https://github.com/j-a-n/lovelace-wallpanel/blob/8c7ce8501849bf6a085841bc70b887ee8842133b/wallpanel.js#L1772). This probably breaks local sourcing and can be done in a better way.

**Comment by j-a-n** [comment] 2024-02-17 10:58
Could you please try, if the issue is fixed with this 
[version](https://github.com/j-a-n/lovelace-wallpanel/blob/7b3dd2f66addb36a038cf208dc7d44b86973bf63/wallpanel.js)?

**Comment by exceldatei** [comment] 2024-02-18 15:00
I try it exactly the same way with the newest wallpanel.js version, but it just shows me a black screen with broken image symbol. The dlna server is integrated correctly in HA

**Comment by j-a-n** [comment] 2024-03-29 11:49
Please try if this is fixed with version 4.25.0

**Comment by SQ6NTI** [comment] 2024-03-31 00:49
It now works in 4.25.0. Thank you!

**Closed** 2024-04-02 07:01 UTC
