### ISSUE TITLE
White bar on custom background

### ISSUE THREAD

**Issue by UMB8998** [j-a-n/lovelace-wallpanel#71] opened 2023-01-11 04:10 UTC
Hello,

I'm using the integration with a panel view to hide the toolbar, but for some reason once the toolbar is hided the screen size doesn't change, that makes the background to have a white bar at the bottom, and the card that we have doesn't occupy the all screen, I'm guessing I'm missing something, but don't know what, does anybody had the same issue?

Thank you

**Comment by j-a-n** [comment] 2023-01-11 08:13
Hello,
seems to be an browser issue.
Which device and browser are you using?

**Comment by UMB8998** [comment] 2023-01-12 23:54
Hello,

I have tried using the native app in Android and Chrome in the computer, both of them have the issue

**Comment by j-a-n** [comment] 2023-01-14 10:26
I don't really have any ideas about that. Maybe another extension is the cause?

**Comment by UMB8998** [comment] 2023-01-16 18:32
ok, let me try it with another install of HA, I will keep you updated. Thanks!

**Comment by RichardHolt56** [comment] 2023-02-01 14:30
I have the same issue. I fixed it (temporarily) by changing the style on the on the  div with the ID "view" from `min-height: calc( 100vh - var(--header-height) - 48px - env(safe-area-inset-top) - env(safe-area-inset-bottom) )` to `min-height: 100vh`
If this could somehow be injected when the hide_toolbar option is enabled, this issue will be fixed.

**Comment by j-a-n** [comment] 2023-02-05 18:06
Thank you, I have implemented your suggestion.
Please try if the issue is fixed in version v4.7.1.

**Comment by RichardHolt56** [comment] 2023-02-05 20:26
I can confirm this fixes both Firefox and Edge for me!

**Closed** 2023-02-05 20:35 UTC
