### ISSUE TITLE
Out of memory browser

### ISSUE THREAD

**Issue by diemon24** [j-a-n/lovelace-wallpanel#209] opened 2024-02-21 19:26 UTC
Hi. After last update all browsers in my all desktop station gives an error message "out of memory" when Wallpanel turns on. 

I can't identify the error and the reason because the browser closes the page.

I only have this stats from mini PC with TV panel in my room:
![image](https://github.com/j-a-n/lovelace-wallpanel/assets/91910101/60a96392-5e5b-490e-a3bf-b8d4a9bb5547)

maybe I should go back to the previous version of Wallpanel?

**Comment by j-a-n** [comment] 2024-02-21 19:36
Perhaps related to #205 ?

**Comment by diemon24** [comment] 2024-02-21 21:50
Wow... this is mushroom card?... This is problem... thx!

**Comment by j-a-n** [comment] 2024-02-21 23:03
Duplicate of #205

**Closed by j-a-n** 2024-02-21 23:03 UTC
