### ISSUE TITLE
White Line on side of screen -- Fully Kiosk on Fire Tablet 10 and Kiosk pro iPad

### ISSUE THREAD

**Issue by Ramias1** [j-a-n/lovelace-wallpanel#186] opened 2023-12-18 16:16 UTC
Two Fire 10's have this and my iPad.  Same Dashboard on computer does not have this.

A white line down the left edge of the screen.

I get to it with:

http://ip:8123/dashboard/monitor?wp_enabled=true&wp_hide_toolbar=true&wp_hide_sidebar=true&wp_idle_time=0&wp_fullscreen=true

I see threads of others who have reported this and it is apparently fixed. Not in my case.  It has pretty much always been like this.

White line is also there if I go to the same URL with Safari on my iPad.  Any ideas?

**Comment by j-a-n** [comment] 2023-12-23 12:36
Please try if v4.23.1 fixes the issue.

**Comment by j-a-n** [comment] 2023-12-31 10:00
Duplicate of #184

**Closed by j-a-n** 2023-12-31 10:00 UTC
