### ISSUE TITLE
Duplicate Menu / Navigation Icon

### ISSUE THREAD

**Issue by OverZealous** [j-a-n/lovelace-wallpanel#112] opened 2023-05-11 18:20 UTC
I'm not sure why, but I'm getting a duplicate navigation or menu icon when WallPanel is installed. I'm not even using WallPanel on this dashboard.

![Screenshot 2023-05-11 at 2 04 38 PM](https://github.com/j-a-n/lovelace-wallpanel/assets/965719/2f627f8e-8708-4248-bc1b-62798d2cd284)

It doesn't appear until after the page has finished loading, and once in a while it doesn't appear at all. It goes away when I remove WallPanel. I also have Kiosk Mode installed, but that doesn't seem to make the menu come or go.

Versions:

- WallPanel: 4.110
- Home Assistant: 2023.5.2
- Supervisor: 2023.04.1
- Operating System: 10.1
-  Frontend: 20230503.3 - latest 

It's possible it's an interaction with another front end extension, but I don't know which ones would affect the menu.

**Comment by bkaufx** [comment] 2023-06-08 03:17
I have the same thing.  Really annoying.

**Comment by bkaufx** [comment] 2023-06-08 03:38
Stepping through the javascript, it is this line that creates the menu item:

https://github.com/j-a-n/lovelace-wallpanel/blob/main/wallpanel.js#L371

`haMenuButton.style.display = (hidden ? "none" : "initial");`

Maybe just remove that line will work.  I don't want that button under any circumstances.

**Comment by bkaufx** [comment] 2023-06-08 03:55
Ok I changed that line to the following and it worked well.  To change it I just edited the js file where hacs installed it and removed the js.gz file.  Then cleared browser cache.

`haMenuButton.style.display = (hidden ? "none" : "none");`

The only issue I have now is these weird arrows still show up and then disappear.  Sometimes its pretty instant and sometimes it takes half a second.  Only in firefox though it seems.  I'm also not sure if this is a WallPanel issue or Home Assistant.

![image](https://github.com/j-a-n/lovelace-wallpanel/assets/31808830/8010fac1-0105-4e33-9771-1b9637cdfa69)

**Comment by OverZealous** [comment] 2023-06-08 13:20
@bkaufx Thanks for looking into it more, I haven't had the time. I went ahead and modified it the way you did. The only place I use WallPanel is with devices that I want to control the menu visibility anyway.

For the `.gz` file, you can recreate it using `gzip -c wallpanel.js > wallpanel.js.gz`. I assume you already know this, but the GZ file is served to improve transfer speeds.

**Comment by j-a-n** [comment] 2023-06-15 22:23
Thanks @bkaufx for looking into this.
The fix is in version 4.12.0.
I don't think the issue with these arrows is caused by wallpanel.

**Closed by j-a-n** 2023-06-15 22:23 UTC

**Comment by bkaufx** [comment] 2023-06-15 22:34
Thanks!
