### ISSUE TITLE
Last home assistant release stopped screensaver

### ISSUE THREAD

**Issue by xgaibtcgd** [j-a-n/lovelace-wallpanel#250] opened 2024-07-05 23:46 UTC
`wallpanel:
  enabled: false
  hide_toolbar: true
  hide_sidebar: true
  fullscreen: true
  image_url: /
  image_fit: cover
  image_list_update_interval: 3600
  display_time: 60
  idle_time: 1`

I have my screen saver images in my HA media folder.  This used to work but since the latest july home assistant upgrade, it stopped showing my images.  Any ideas? 

Only thing i see in my HA logs is:

Logger: frontend.js.latest.202407050
Source: components/system_log/__init__.py:333
First occurred: 1:55:59 PM (6 occurrences)
Last logged: 4:44:35 PM

Uncaught error from Chrome 126.0.0.0 on Windows 10 TypeError: Cannot read properties of undefined (reading 'editMode') _createCardElement (src/panels/lovelace/views/hui-view.ts:79:36) /hacsfiles/lovelace-wallpanel/wallpanel.js:1146:53 WallpanelView.createInfoBoxContent (/hacsfiles/lovelace-wallpanel/wallpanel.js:1132:17) WallpanelView.startScreensaver (/hacsfiles/lovelace-wallpanel/wallpanel.js:2090:8) WallpanelView.timer (/hacsfiles/lovelace-wallpanel/wallpanel.js:769:10)
Uncaught error from Chrome 126.0.0.0 on Windows 10 Script error. null @:0:0

**Comment by xgaibtcgd** [comment] 2024-07-06 01:30
Reinstalling seemed to get the screensaver to work again - still getting those same errors so not sure if that's anything i need to look into but it all seems functional now.

**Comment by joehill1810** [comment] 2024-07-06 18:25
Happened to me as well. Had to uninstall and reinstall to regain functionality

**Comment by j-a-n** [comment] 2024-07-06 19:19
Duplicate of #246

**Closed by j-a-n** 2024-07-06 19:19 UTC
